#!/bin/bash
# Проверка логов ноды и конфигурации подключения

echo "🔍 Проверка логов ноды и конфигурации"
echo "======================================"
echo ""

NODE_IP="185.126.67.67"

echo "📋 Выполните на Node Server (185.126.67.67):"
echo ""
echo "1️⃣  Проверка логов ноды (последние 50 строк):"
echo "   docker logs anomaly-node --tail=50"
echo ""
echo "2️⃣  Проверка конфигурации .env.node:"
echo "   cat .env.node | grep -E 'CONTROL_SERVER_URL|SERVICE_PROTOCOL|UVICORN'"
echo ""
echo "3️⃣  Проверка переменных окружения контейнера:"
echo "   docker exec anomaly-node env | grep -E 'CONTROL_SERVER|SERVICE_PROTOCOL|UVICORN|SSL'"
echo ""
echo "4️⃣  Проверка, слушает ли нода на порту 62050:"
echo "   docker exec anomaly-node netstat -tlnp | grep 62050 || ss -tlnp | grep 62050"
echo ""
echo "5️⃣  Проверка файлов сертификатов внутри контейнера:"
echo "   docker exec anomaly-node ls -la /var/lib/marzban-node/ssl/certificate.pem"
echo "   docker exec anomaly-node ls -la /var/lib/marzban-node/node-certs/certificate.pem"
echo "   docker exec anomaly-node ls -la /var/lib/marzban-node/node-certs/key.pem"
echo ""
echo "6️⃣  Проверка, может ли нода подключиться к Control Server:"
echo "   docker exec anomaly-node python3 -c \""
echo "   import urllib.request, ssl"
echo "   ssl_context = ssl.create_default_context()"
echo "   ssl_context.check_hostname = False"
echo "   ssl_context.verify_mode = ssl.CERT_NONE"
echo "   try:"
echo "       req = urllib.request.Request('https://panel.anomaly-connect.online:62050/')"
echo "       with urllib.request.urlopen(req, timeout=5, context=ssl_context) as resp:"
echo "           print(f'SUCCESS: {resp.getcode()}')"
echo "   except Exception as e:"
echo "       print(f'ERROR: {str(e)}')"
echo "   \""
echo ""
echo "💡 Или выполните все команды одной строкой:"
echo "   ssh root@$NODE_IP 'cd /opt/Anomaly && docker logs anomaly-node --tail=50 && echo \"---\" && cat .env.node | grep -E \"CONTROL_SERVER_URL|SERVICE_PROTOCOL|UVICORN\" && echo \"---\" && docker exec anomaly-node env | grep -E \"CONTROL_SERVER|SERVICE_PROTOCOL|UVICORN|SSL\"'"
echo ""

