#!/bin/bash
# Детальная диагностика проблемы подключения к ноде

echo "🔍 Детальная диагностика проблемы подключения к ноде"
echo "===================================================="
echo ""

NODE_IP="185.126.67.67"

echo "📋 Выполните на Node Server (185.126.67.67):"
echo ""
echo "1️⃣  Проверка, может ли нода принимать подключения локально:"
echo "   docker exec anomaly-node python3 -c \""
echo "   import urllib.request, ssl"
echo "   ssl_context = ssl.create_default_context()"
echo "   ssl_context.check_hostname = False"
echo "   ssl_context.verify_mode = ssl.CERT_NONE"
echo "   try:"
echo "       req = urllib.request.Request('https://localhost:62050/')"
echo "       with urllib.request.urlopen(req, timeout=5, context=ssl_context) as resp:"
echo "           print(f'SUCCESS: {resp.getcode()}')"
echo "   except Exception as e:"
echo "       print(f'ERROR: {str(e)}')"
echo "   \""
echo ""
echo "2️⃣  Проверка логов ноды в реальном времени (во время попытки подключения):"
echo "   docker logs -f anomaly-node"
echo "   (Затем на Control Server выполните: ./test-node-from-control.sh)"
echo ""
echo "3️⃣  Проверка, какие процессы слушают на порту 62050:"
echo "   netstat -tlnp | grep 62050"
echo "   или"
echo "   ss -tlnp | grep 62050"
echo ""
echo "4️⃣  Проверка firewall:"
echo "   ufw status"
echo "   или"
echo "   iptables -L -n | grep 62050"
echo ""
echo "5️⃣  Проверка, правильно ли настроен marzban-node:"
echo "   docker exec anomaly-node env | grep -E 'UVICORN|SERVICE|SSL'"
echo ""
echo "6️⃣  Проверка версии marzban-node:"
echo "   docker exec anomaly-node python3 -c \"import marzban_node; print(marzban_node.__version__)\" 2>/dev/null || \\"
echo "   docker exec anomaly-node cat /app/version.txt 2>/dev/null || \\"
echo "   docker exec anomaly-node ls -la /app/ | head -10"
echo ""
echo "💡 Возможные решения:"
echo "   1. Проверьте документацию marzban-node: https://github.com/gozargah/marzban-node"
echo "   2. Возможно, нужно использовать другой протокол (не REST)"
echo "   3. Возможно, нужно добавить дополнительные переменные окружения"
echo "   4. Проверьте, что версия marzban-node совместима с версией Marzban на Control Server"
echo ""

